# Schema for the configuration files of the snowplow module.

snowplow.settings:
  type: config_object
  label: 'Snowplow settings'
  mapping:
    app_id:
      type: string
    app_endpoint:
      type: string
    track_logins:
      type: boolean
    track_logout:
      type: boolean
    track_new_user:
      type: boolean
    trackmessages:
      type: string
