<?php

/**
 * @file
 * Snowplow javascript module adds the js tracker to pages.
 */

// API call to get latest version of snowplow js.
// api.github.com/repos/snowplow/snowplow-javascript-tracker/releases
/**
 * Implements hook_form_alter().
 */
function snowplow_js_form_snowplow_admin_settings_alter(&$form, &$form_state, $form_id) {
  //var_dump($form_id);
  //$form['attached'] = "Add some js here for form tracking";
}

function snowplow_js_form_alter(&$form, &$form_state, $form_id) {
  //var_dump($form_id);
}

